project '/Users/thomas/Apps/te-online--timemanager-ios/TimeManager/TimeManager.xcodeproj'
workspace '/Users/thomas/Apps/te-online--timemanager-ios/TimeManager/TimeManager/TimeManager.xcworkspace'

platform :ios, '8.0'
use_frameworks!

target 'TimeManager' do
    pod 'SwiftyJSON'
    pod 'Charts'
end